### PR TITLE
Add link to programming guide to the widget-store apps

### PR DESCRIPTION
**Pull request by lanice**
image
image

### CODE REVIEW

**Review by chuck-dbos — APPROVED** [review]

**Comment by apoliakov** [comment]
@lanice One thought from me - I would make it bigger, bolder - especially on the Desktop side. Like... as big as the "Buy" button. 

Also while at it - if I can beg for a quick favor - could you set the Typescript scheduled workflow to 1/20s like we did in Py?

**Comment by lanice** [comment]
> @lanice One thought from me - I would make it bigger, bolder - especially on the Desktop side. Like... as big as the "Buy" button.


@apoliakov  Like this? I personally find it a bit *too* bold, but I guess for the purpose of really putting it out there, it could make sense.
image

**Comment by lanice** [comment]
> Also while at it - if I can beg for a quick favor - could you set the Typescript scheduled workflow to 1/20s like we did in Py?

Done!

**Comment by apoliakov** [comment]
I do think that's better. Maybe add a larger margin between the text and the top picture and then you don't have to make it bold font (same font size but not bold)? 

But judging by what happened to the app deploy URL, I do think this will perform better

**Comment by lanice** [comment]
image
Increased it a bit or mobile, but not as much as for desktop:
image

**Comment by apoliakov** [comment]
Nice! I like this one

**Pull request merged**
